CREATE TYPE estado_usuario AS ENUM ('activo', 'bloqueado', 'pendiente');
CREATE TYPE nivel_acceso AS ENUM ('ver', 'editar', 'solo_lectura');
CREATE TYPE accion_auditoria AS ENUM ('crear', 'leer', 'actualizar', 'borrar', 'exportar', 'restaurar');
CREATE TYPE severidad AS ENUM ('info', 'bajo', 'medio', 'alto', 'critico');
CREATE TYPE sexo AS ENUM ('M', 'F');
CREATE TYPE estado_receta AS ENUM ('borrador', 'firmada', 'cancelada');
CREATE TYPE estado_cita AS ENUM ('agendada', 'atendida', 'cancelada', 'falta', 'reagendada');
CREATE TYPE estandar_interop AS ENUM ('HL7', 'FHIR', 'CUSTOM');
CREATE TYPE estado_condicion_paciente AS ENUM ('activo', 'resuelto', 'remision');

CREATE TABLE roles (
  id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL UNIQUE,
  descripcion VARCHAR(255)
);

CREATE TABLE permisos (
  id_permiso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(100) NOT NULL UNIQUE,
  descripcion VARCHAR(255)
);

CREATE TABLE roles_permisos (
  id_rol BIGINT NOT NULL,
  id_permiso BIGINT NOT NULL,
  PRIMARY KEY (id_rol, id_permiso)
);

CREATE TABLE usuarios (
  id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_completo VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  telefono VARCHAR(30),
  contrasena VARCHAR(255) NOT NULL,
  estado_2fa BOOLEAN NOT NULL DEFAULT FALSE,
  estado estado_usuario NOT NULL DEFAULT 'activo',
  id_rol BIGINT NOT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE profesionales (
  id_profesional BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT NOT NULL,
  cedula VARCHAR(50),
  especialidad VARCHAR(120),
  creado_en TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE pacientes (
  id_paciente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT,
  nombre_completo VARCHAR(150) NOT NULL,
  curp VARCHAR(18) UNIQUE,
  fecha_nacimiento DATE,
  sexo sexo,
  email VARCHAR(150),
  telefono VARCHAR(30),
  nombre_emergencia VARCHAR(150),
  telefono_emergencia VARCHAR(30),
  seguro VARCHAR(120),
  creado_en TIMESTAMP NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE direcciones (
  id_direccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_paciente BIGINT NOT NULL,
  calle VARCHAR(200),
  numero_interior VARCHAR(20),
  numero_exterior VARCHAR(20),
  colonia VARCHAR(120),
  ciudad VARCHAR(80),
  estado VARCHAR(80),
  codigo_postal VARCHAR(15)
);

CREATE TABLE historial_medico (
  id_historial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_paciente BIGINT NOT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMP NOT NULL DEFAULT now(),
  estado VARCHAR(30),
  etiqueta VARCHAR(80)
);

CREATE TABLE medicamentos (
  id_medicamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL UNIQUE,
  descripcion VARCHAR(255)
);

CREATE TABLE catalogo_condiciones (
  id_condicion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL UNIQUE,
  codigo_serial VARCHAR(30)
);

CREATE TABLE catalogo_alergias (
  id_alergia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE catalogo_estudios (
  id_tipo_estudio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE pacientes_alergias (
  id_alergia BIGINT NOT NULL,
  id_historial BIGINT NOT NULL,
  reaccion VARCHAR(200),
  severidad severidad,
  registrado_en TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (id_alergia, id_historial) 
);

CREATE TABLE pacientes_condiciones (
  id_condicion BIGINT NOT NULL,
  id_historial BIGINT NOT NULL,
  estado estado_condicion_paciente NOT NULL DEFAULT 'activo',
  notas VARCHAR(255),
  diagnosticado_en DATE,
  PRIMARY KEY (id_condicion, id_historial) 
);

CREATE TABLE pacientes_cirugias (
  id_cirugia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_historial BIGINT NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  fecha_cirugia DATE,
  notas VARCHAR(255)
);

CREATE TABLE pacientes_medicacion_actual (
  id_medicamento BIGINT NOT NULL,
  id_historial BIGINT NOT NULL,
  dosis VARCHAR(80),
  frecuencia VARCHAR(80),
  fecha_inicio DATE,
  fecha_fin DATE,
  notas VARCHAR(255),
  PRIMARY KEY (id_medicamento, id_historial)
);


CREATE TABLE consultas (
  id_consulta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_profesional BIGINT NOT NULL,
  id_historial BIGINT NOT NULL,
  programada_en TIMESTAMP NOT NULL,
  motivo VARCHAR(200),
  diagnostico VARCHAR(255),
  notas TEXT,
  seguimiento_en TIMESTAMP,
  creado_en TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE signos_vitales (
  id_signo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_consulta BIGINT,
  id_historial BIGINT NOT NULL,
  medido_en TIMESTAMP NOT NULL,
  peso_kg NUMERIC(6, 2),
  estatura_cm NUMERIC(6, 2),
  imc NUMERIC(5, 2),
  presion_arterial_s SMALLINT,
  presion_arterial_d SMALLINT,
  frec_cardiaca_bpm SMALLINT,
  temperatura_c NUMERIC(4, 1)
);

CREATE TABLE recetas (
  id_receta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_profesional BIGINT NOT NULL,
  id_historial BIGINT NOT NULL,
  emitida_en TIMESTAMP NOT NULL DEFAULT now(),
  firma VARCHAR(255),
  estado estado_receta NOT NULL DEFAULT 'borrador'
);

CREATE TABLE desc_receta (
  id_descr BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_receta BIGINT NOT NULL,
  id_medicamento BIGINT NOT NULL,
  id_historial BIGINT,
  dosis VARCHAR(80) NOT NULL,
  frecuencia VARCHAR(80) NOT NULL,
  duracion_dias SMALLINT,
  instrucciones VARCHAR(255)
);

CREATE TABLE estudios (
  id_estudio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_historial BIGINT NOT NULL,
  solicitado_por BIGINT,
  id_tipo_estudio BIGINT NOT NULL,
  solicitado_en TIMESTAMP NOT NULL DEFAULT now(),
  resultado_en TIMESTAMP
);

CREATE TABLE citas (
  id_cita BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_profesional BIGINT NOT NULL,
  programada_en TIMESTAMP NOT NULL,
  motivo VARCHAR(200),
  estado estado_cita NOT NULL DEFAULT 'agendada',
  creado_en TIMESTAMP NOT NULL DEFAULT now()
);


CREATE TABLE historial_acceso (
  id_concesion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_paciente BIGINT NOT NULL,
  id_usuario_beneficiario BIGINT NOT NULL,
  nivel nivel_acceso NOT NULL DEFAULT 'ver',
  expira_en TIMESTAMP,
  creado_en TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE (id_paciente, id_usuario_beneficiario)
);

CREATE TABLE bitacora_auditoria (
  id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario_actor BIGINT,
  entidad VARCHAR(80) NOT NULL,
  id_entidad BIGINT,
  accion accion_auditoria NOT NULL,
  detalle JSONB,
  ip VARCHAR(45),
  creado_en TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_bitacora_auditoria_entidad ON bitacora_auditoria (entidad, id_entidad);

CREATE TABLE notificaciones (
  id_notificacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT NOT NULL,
  tipo VARCHAR(80) NOT NULL,
  carga JSONB,
  enviado_en TIMESTAMP,
  leido_en TIMESTAMP,
  creado_en TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_notificaciones_usuario_enviado ON notificaciones (id_usuario, enviado_en);

CREATE TABLE historial_versiones (
  id_version BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidad VARCHAR(80) NOT NULL,
  id_entidad BIGINT NOT NULL,
  id_historial BIGINT,
  numero_version INT NOT NULL,
  captura JSONB NOT NULL,
  cambiado_por BIGINT,
  creado_en TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE (entidad, id_entidad, numero_version)
);

CREATE TABLE alertas_clinicas (
  id_alerta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_historial BIGINT NOT NULL,
  entidad_origen VARCHAR(80) NOT NULL,
  id_origen BIGINT,
  severidad severidad NOT NULL,
  mensaje VARCHAR(255) NOT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT now(),
  resuelto_en TIMESTAMP
);
CREATE INDEX idx_alertas_clinicas_creado_en ON alertas_clinicas (creado_en);

CREATE TABLE archivos (
  id_archivo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidad_propietaria VARCHAR(80) NOT NULL,
  id_propietario BIGINT NOT NULL,
  id_historial BIGINT,
  nombre_archivo VARCHAR(255) NOT NULL,
  tipo_formato VARCHAR(100) NOT NULL,
  ruta_almacenamiento VARCHAR(400) NOT NULL,
  subido_por BIGINT,
  subido_en TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_archivos_propietario ON archivos (entidad_propietaria, id_propietario);

ALTER TABLE roles_permisos
ADD CONSTRAINT fk_roles_permisos_rol
FOREIGN KEY (id_rol) REFERENCES roles (id_rol);

ALTER TABLE roles_permisos
ADD CONSTRAINT fk_roles_permisos_permiso
FOREIGN KEY (id_permiso) REFERENCES permisos (id_permiso);

ALTER TABLE usuarios
ADD CONSTRAINT fk_usuarios_rol
FOREIGN KEY (id_rol) REFERENCES roles (id_rol);

ALTER TABLE profesionales
ADD CONSTRAINT fk_profesionales_usuario
FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE pacientes
ADD CONSTRAINT fk_pacientes_usuario
FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE direcciones
ADD CONSTRAINT fk_direcciones_paciente
FOREIGN KEY (id_paciente) REFERENCES pacientes (id_paciente);

ALTER TABLE historial_medico
ADD CONSTRAINT fk_historial_medico_paciente
FOREIGN KEY (id_paciente) REFERENCES pacientes (id_paciente);

ALTER TABLE historial_acceso
ADD CONSTRAINT fk_historial_acceso_paciente
FOREIGN KEY (id_paciente) REFERENCES pacientes (id_paciente);

ALTER TABLE historial_acceso
ADD CONSTRAINT fk_historial_acceso_usuario_beneficiario
FOREIGN KEY (id_usuario_beneficiario) REFERENCES usuarios (id_usuario);

ALTER TABLE pacientes_alergias
ADD CONSTRAINT fk_pa_alergia
FOREIGN KEY (id_alergia) REFERENCES catalogo_alergias (id_alergia);

ALTER TABLE pacientes_alergias
ADD CONSTRAINT fk_pa_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

ALTER TABLE pacientes_condiciones
ADD CONSTRAINT fk_pc_condicion
FOREIGN KEY (id_condicion) REFERENCES catalogo_condiciones (id_condicion);

ALTER TABLE pacientes_condiciones
ADD CONSTRAINT fk_pc_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

ALTER TABLE pacientes_cirugias
ADD CONSTRAINT fk_pacientes_cirugias_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

ALTER TABLE pacientes_medicacion_actual
ADD CONSTRAINT fk_pma_medicamento
FOREIGN KEY (id_medicamento) REFERENCES medicamentos (id_medicamento);

ALTER TABLE pacientes_medicacion_actual
ADD CONSTRAINT fk_pma_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

ALTER TABLE consultas
ADD CONSTRAINT fk_consultas_profesional
FOREIGN KEY (id_profesional) REFERENCES profesionales (id_profesional);

ALTER TABLE consultas
ADD CONSTRAINT fk_consultas_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

ALTER TABLE signos_vitales
ADD CONSTRAINT fk_sv_consulta
FOREIGN KEY (id_consulta) REFERENCES consultas (id_consulta);

ALTER TABLE signos_vitales
ADD CONSTRAINT fk_sv_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

ALTER TABLE recetas
ADD CONSTRAINT fk_recetas_profesional
FOREIGN KEY (id_profesional) REFERENCES profesionales (id_profesional);

ALTER TABLE recetas
ADD CONSTRAINT fk_recetas_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

ALTER TABLE desc_receta
ADD CONSTRAINT fk_dr_receta
FOREIGN KEY (id_receta) REFERENCES recetas (id_receta);

ALTER TABLE desc_receta
ADD CONSTRAINT fk_dr_medicamento
FOREIGN KEY (id_medicamento) REFERENCES medicamentos (id_medicamento);

ALTER TABLE desc_receta
ADD CONSTRAINT fk_dr_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

ALTER TABLE alertas_clinicas
ADD CONSTRAINT fk_alertas_clinicas_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

ALTER TABLE estudios
ADD CONSTRAINT fk_estudios_tipo
FOREIGN KEY (id_tipo_estudio) REFERENCES catalogo_estudios (id_tipo_estudio);

ALTER TABLE estudios
ADD CONSTRAINT fk_estudios_solicitante
FOREIGN KEY (solicitado_por) REFERENCES profesionales (id_profesional);

ALTER TABLE estudios
ADD CONSTRAINT fk_estudios_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

ALTER TABLE archivos
ADD CONSTRAINT fk_archivos_subido_por
FOREIGN KEY (subido_por) REFERENCES usuarios (id_usuario);

ALTER TABLE archivos
ADD CONSTRAINT fk_archivos_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

ALTER TABLE citas
ADD CONSTRAINT fk_citas_profesional
FOREIGN KEY (id_profesional) REFERENCES profesionales (id_profesional);

ALTER TABLE bitacora_auditoria
ADD CONSTRAINT fk_ba_usuario_actor
FOREIGN KEY (id_usuario_actor) REFERENCES usuarios (id_usuario);

ALTER TABLE notificaciones
ADD CONSTRAINT fk_notificaciones_usuario
FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE historial_versiones
ADD CONSTRAINT fk_hv_cambiado_por
FOREIGN KEY (cambiado_por) REFERENCES usuarios (id_usuario);

ALTER TABLE historial_versiones
ADD CONSTRAINT fk_hv_historial
FOREIGN KEY (id_historial) REFERENCES historial_medico (id_historial);

CREATE INDEX idx_signos_vitales_historial ON signos_vitales (id_historial);
CREATE INDEX idx_alertas_clinicas_historial ON alertas_clinicas (id_historial);
CREATE INDEX idx_recetas_historial ON recetas (id_historial);
CREATE INDEX idx_consultas_historial ON consultas (id_historial);
CREATE INDEX idx_estudios_historial ON estudios (id_historial);
